[BIA-475] - DRAFT - Creates a new workflow to build AMT.
Ed-Fi-Alliance-OSS/Ed-Fi-Analytics-Middle-Tier pull request #149
Opened 2021-11-05 19:35 UTC by DavidJGapCR

2021-11-05 20:04 UTC, stephenfuqua requested changes
Small comments. On the right track!

2021-11-05 22:37 UTC, DavidJGapCR commented on .github/workflows/build.yml
> +name: AMT Build
Fixed.

2021-11-05 22:37 UTC, DavidJGapCR commented on .github/workflows/build.yml
> +      - main
Fixed

2021-11-08 14:52 UTC, stephenfuqua approved these changes

2021-11-08 22:17 UTC, jleiva-gap approved these changes

2021-11-08 22:32 UTC, merged