[BIA-483] Creates the StudentAssessmentFact View.
Ed-Fi-Alliance-OSS/Ed-Fi-Analytics-Middle-Tier pull request #20
Opened 2020-12-18 20:12 UTC by DavidJGapCR

2021-01-05 21:18 UTC, kurtjohnson-HS reviewed
I tested the install against v3.1, v3.2, v3.3, v3.4, and v5.0 for MSSQL. The Postgres Console migration fails - as you already know.

I did receive 22 errors after commenting out the namespace in the joins - more than 1 error as expected. 
![image](https://user-images.githubusercontent.com/63315476/103699845-2b353600-4f69-11eb-890b-ea2fe9095f1a.png)

2021-01-05 23:09 UTC, kurtjohnson-HS requested changes
We still need to resolve the question of whether or not to change the edfi.Assessment  table join to the asmt_AssessmentDim view to match the work item.

2021-01-06 15:24 UTC, DavidJGapCR commented on src/EdFi.AnalyticsMiddleTier.DataStandard31/Asmt/MSSQL/0001-View-StudentAssessmentFact-Create.sql
> +        edfi.Assessment
I don't think it says we have to use the AssessmentDim view. I think what it says is that this field is going to be used as a key to associate StudentAssessmentFact with AssessmentDim. Actually, if you see the other fields: StudentSchoolKey and SchoolKey it says basically the same thing, but we don't use these views.
We usually don't join views with other views. If I remember correctly there is just one case where we did that. I don't remember where exactly.

2021-01-06 15:25 UTC, DavidJGapCR commented
> I tested the install against v3.1, v3.2, v3.3, v3.4, and v5.0 for MSSQL. The Postgres Console migration fails - as you already know.
> 
> I did receive 22 errors after commenting out the namespace in the joins - more than 1 error as expected.
> ![image](https://user-images.githubusercontent.com/63315476/103699845-2b353600-4f69-11eb-890b-ea2fe9095f1a.png)

Just to confirm we are on the same page.
You can comment out not only the namespace condition in the joins but any condition in a join with more than 1 condition.
For example, lines:
28,29,44,45,46,47,50,51,52,53,71,74
Basically, where there is an AND or OR in a join, you can comment out one side or the other.
Let me know if this makes sense.

2021-01-06 15:46 UTC, kurtjohnson-HS commented
> Just to confirm we are on the same page.
> You can comment out not only the namespace condition in the joins but any condition in a join with more than 1 condition.
> For example, lines:
> 28,29,44,45,46,47,50,51,52,53,71,74
> Basically, where there is an AND or OR in a join, you can comment out one side or the other.
> Let me know if this makes sense.

That was what I did, so we are on the same page. I went through each one and verified that testing threw exceptions when the condition was commented out.

2021-01-06 15:48 UTC, kurtjohnson-HS approved these changes

2021-01-06 15:49 UTC, merged