[BIA-1301]: Update fn_GetStudentGradesSummary to use descriptor constant
Ed-Fi-Alliance-OSS/Ed-Fi-Analytics-Middle-Tier pull request #228
Opened 2022-12-14 00:57 UTC by jegasape

- Updated fn_GetStudentGradesSummary to use descriptor constant

2022-12-14 14:59 UTC, jleiva-gap requested changes
You shouldn't modify the old scripts. Please add a new script with the suffix Alter and the corresponding numeration.

2022-12-14 21:36 UTC, DavidJGapCR commented
You changed MSSQL, but you are missing Postgres.

2022-12-14 21:40 UTC, DavidJGapCR commented
![image](https://user-images.githubusercontent.com/16614428/207720442-87e7c029-b9d0-457a-bbd9-2c11e7730ac7.png)
You can see here the current script on the left, and the new script on the right. Why did we remove the join to `edfi.GradingPeriod` and the `order by` clause?

2022-12-19 21:00 UTC, jleiva-gap approved these changes

2022-12-19 21:26 UTC, DavidJGapCR approved these changes

2022-12-19 21:26 UTC, merged