BIA-676 Add StudentProgramDim view to collection
Ed-Fi-Alliance-OSS/Ed-Fi-Analytics-Middle-Tier pull request #45
Opened 2021-05-13 22:22 UTC by bptillman

This adds a new StudentProgramDim view to the analytics base collection so that going forward, we can query it instead of querying the ODS directly.
Tests have been added for when a record does and does not exist in the view along with testing when a student is in multiple programs ensuring that multiple rows come back from the view. If any additional tests should be added please let me know.

2021-05-13 22:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Ed-Fi-Alliance-OSS/Ed-Fi-Analytics-Middle-Tier?pullRequest=45) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Ed-Fi-Alliance-OSS/Ed-Fi-Analytics-Middle-Tier?pullRequest=45) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Ed-Fi-Alliance-OSS/Ed-Fi-Analytics-Middle-Tier?pullRequest=45) it.</sub>

2021-05-13 22:37 UTC, jleiva-gap requested changes
DS 2. If I comment out the following lines, tests should failed, but all test are green.

1. 25
2. 26
3. 27

    DS 3. If I comment out the following lines, tests should failed, but all test are green.

1. 25
2. 26
3. 27

You need to add more records so that the join conditions fail if any are removed in the view script.

2021-05-17 16:29 UTC, bptillman commented
> 
> 
> ```
> DS 2. If I comment out the following lines, tests should failed, but all test are green.
> ```
> 
>     1. 25
> 
>     2. 26
> 
>     3. 27
>        DS 3. If I comment out the following lines, tests should failed, but all test are green.
> 
>     4. 25
> 
>     5. 26
> 
>     6. 27
> 
> 
> You need to add more records so that the join conditions fail if any are removed in the view script.

I have updated each of the data inserts to insert an additional program/org so that when the and conditions are commented out in the join, the view will produce extra results.

2021-05-17 19:55 UTC, jleiva-gap requested changes

2021-05-17 19:55 UTC, jleiva-gap commented on src/EdFi.AnalyticsMiddleTier.DataStandard2/Base/MSSQL/0025-View-StudentProgramDim-Create.sql
> +        AND StudentProgram.ProgramTypeId = Program.ProgramTypeId
If I comment out this line, test are not failing. More rows are needed to validate this JOIN (e.g. Add a new program with different ProgramTypeId, but with same ProgramName and EducationOrganizationId of other row.

2021-05-17 19:55 UTC, jleiva-gap commented on src/EdFi.AnalyticsMiddleTier.DataStandard31/Base/MSSQL/0023-View-StudentProgramDim-Create.sql
> +        AND StudentProgram.ProgramTypeDescriptorId = Program.ProgramTypeDescriptorId
If I comment out this line, test are not failing. More rows are needed to validate this JOIN (e.g. Add a new program with different ProgramTypeDescriptorId, but with same ProgramName and EducationOrganizationId of other row.

2021-05-17 19:55 UTC, jleiva-gap commented on src/EdFi.AnalyticsMiddleTier.DataStandard32/Base/MSSQL/0023-View-StudentProgramDim-Create.sql
> +        AND StudentProgram.ProgramTypeDescriptorId = Program.ProgramTypeDescriptorId
If I comment out this line, test are not failing. More rows are needed to validate this JOIN (e.g. Add a new program with different ProgramTypeDescriptorId, but with same ProgramName and EducationOrganizationId of other row.

2021-05-17 22:26 UTC, jleiva-gap approved these changes

2021-05-17 23:29 UTC, merged