[LMS-386] Change from schoolyearkey to schoolyear in PostgreSQL
Ed-Fi-Alliance-OSS/Ed-Fi-Analytics-Middle-Tier pull request #79
Opened 2021-08-16 22:25 UTC by lalrg

2021-08-16 22:39 UTC, stephenfuqua commented
Because the existing file was a mistake, and has not been released yet, I asked Luis to modify instead of adding a new file. Not something we do often, but basically safe in this regard IMHO. @bptillman.

2021-08-16 22:45 UTC, stephenfuqua reviewed
The change looks good visually. Waiting to see the TeamCity build process work before merging.

2021-08-16 23:20 UTC, bptillman commented
> 
> 
> Because the existing file was a mistake, and has not been released yet, I asked Luis to modify instead of adding a new file. Not something we do often, but basically safe in this regard IMHO. @bptillman.

That is fine with me, but the file should keep the structure of DROP IF EXISTS and then CREATE. 

> 
> 
> Because the existing file was a mistake, and has not been released yet, I asked Luis to modify instead of adding a new file. Not something we do often, but basically safe in this regard IMHO. @bptillman.

That is fine with me as well in this instance. One thing I did notice is that the structure of the script was changed from DROP IF EXISTS and CREATE to just a CREATE OR REPLACE VIEW and my understanding thus far of AMT was that for any Postgres view alterations we did the DROP IF EXISTS and CREATE to better handle if columns changed, since the migration scripts will throw an error like they did in this instance
`cannot change name of view column "schoolyearkey" to "schoolyear" `

2021-08-17 02:18 UTC, stephenfuqua requested changes

2021-08-17 02:18 UTC, stephenfuqua commented on src/EdFi.AnalyticsMiddleTier.DataStandard32/Base/PostgreSQL/0034-View-AcademicTimePeriodDim-Alter.sql
> +CREATE OR REPLACE VIEW analytics.AcademicTimePeriodDim
@lalrg please see @bptillman 's comment about dropping the view first.

2021-08-17 17:43 UTC, stephenfuqua approved these changes

2021-08-17 17:43 UTC, stephenfuqua commented
@bptillman can you do a final review & approval before we merge this, since it is part of the core view collection?

2021-08-17 17:59 UTC, bptillman commented
> 
> 
> @bptillman can you do a final review & approval before we merge this, since it is part of the core view collection?

Can do

2021-08-17 18:27 UTC, bptillman approved these changes

2021-08-17 19:22 UTC, merged